name: Build LLVM

on:
  push:
    branches:
      - run-actions
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write

env:
  PYTHON_VERSION: 3.13.5
  LLVM_VERSION: 20.1.7

jobs:
  configure-build-and-package-llvm-ubutnu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: llvm/llvm-project
          ref: llvmorg-${{ env.LLVM_VERSION }}

      - name: Download release Python
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'FZ-Collage/python-prebuilts'
          version: 'tags/v${{ env.PYTHON_VERSION }}'
          file: 'python-${{ env.PYTHON_VERSION }}-linux-x86_64.zip'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Python to /usr
        run: |
          sudo unzip -q -o python-${{ env.PYTHON_VERSION }}-linux-x86_64.zip -d /usr/local

      - name: Configure and build LLVM
        run: |
          cd llvm
          cmake -G Ninja -B build -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++ \
            -DLLVM_ENABLE_PROJECTS="clang;lld;clang-tools-extra;lldb" \
            -DCMAKE_INSTALL_PREFIX=llvm-${{ env.LLVM_VERSION }}-linux-x86_64 \
            -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_C_FLAGS="-fPIC" \
            -DCMAKE_CXX_FLAGS="-fPIC"
          cmake --build build --config Release
          cmake --install build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: llvm-${{ env.LLVM_VERSION }}-linux-x86_64
          path: llvm/llvm-${{ env.LLVM_VERSION }}-linux-x86_64
