name: Build LLVM Ubuntu (x86_64)

on:
  push:
    branches:
      - run-actions
      - main
      - linux-actions
  pull_request:
    branches:
      - main
permissions:
  contents: write

env:
  LLVM_VERSION: "22.0.0git"

jobs:
  build-llvm-ubuntu-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: ZeunO8/llvm-project
          ref: c-index-workaround

      - name: Configure LLVM
        run: |
          cd llvm
          cmake -G Ninja -B build \
            -D CMAKE_C_COMPILER=clang \
            -D CMAKE_CXX_COMPILER=clang++ \
            -DLLVM_ENABLE_PROJECTS="clang;lld;clang-tools-extra;lldb" \
            "-DCMAKE_INSTALL_PREFIX=llvm-${{ env.LLVM_VERSION }}-linux-x86_64" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_FLAGS="-fPIC" \
            -DCMAKE_CXX_FLAGS="-fPIC" \
            -DBUILD_SHARED_LIBS=OFF \
            -DLLVM_BUILD_STATIC=ON \
            -DLLDB_ENABLE_PYTHON=OFF \
            -DLLDB_ENABLE_LUA=OFF \
            -DLLDB_ENABLE_LIBXML2=OFF \
            -DLLDB_ENABLE_LZMA=OFF \
            -DLLDB_ENABLE_CURSES=OFF \
            -DLLDB_ENABLE_LIBEDIT=OFF \
            -DLLVM_BUILD_EXAMPLES=OFF -DLLVM_INCLUDE_EXAMPLES=OFF \
            -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_UTILS=OFF \
            -DLLVM_BUILD_TESTS=OFF -DLLVM_INCLUDE_TESTS=OFF \
            -DLLVM_BUILD_BENCHMARKS=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF \
            -DLLVM_ENABLE_ASSERTIONS=OFF -DCLANG_INCLUDE_TESTS=OFF \
            -DLLDB_INCLUDE_TESTS=OFF \
            -DLIBCLANG_BUILD_STATIC=ON -DLLVM_ENABLE_PIC=ON \
            -DLLVM_ENABLE_RTTI=ON \
            -DLLVM_LINK_LLVM_DYLIB=OFF -DLLVM_BUILD_LLVM_C_DYLIB=OFF \
            -DHAVE_THREAD_SAFETY_ATTRIBUTES=0 -DHAVE_POSIX_REGEX=0 \
            -DHAVE_STEADY_CLOCK=0 -DLLVM_ADD_TESTS=OFF \
            -DLLDB_INCLUDE_TESTS=OFF -DCLANG_INCLUDE_TESTS=OFF

      - name: Build LLVM
        run: |
          cd llvm
          cmake --build build --config Release

      - name: Install LLVM
        run: |
          cd llvm
          cmake --install build

      - name: tar.gz files
        run: |
          cd llvm/llvm-${{ env.LLVM_VERSION }}-linux-x86_64
          tar -cvzf ../../llvm-${{ env.LLVM_VERSION }}-linux-x86_64.tar.gz *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: llvm-${{ env.LLVM_VERSION }}-linux-x86_64
          path: llvm-${{ env.LLVM_VERSION }}-linux-x86_64.tar.gz
