name: Build LLVM MacOS (ARM)

on:
  push:
    branches:
      - run-actions
      - main
      - macos-actions
  pull_request:
    branches:
      - main
permissions:
  contents: write

env:
  LLVM_VERSION: "22.0.0git"

jobs:
  build-llvm-macos-arm:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: ZeunO8/llvm-project
          ref: c-index-workaround

      - name: Install Swig
        run: brew install swig

      - name: Configure LLVM
        run: |
          cd llvm
          cmake -G Ninja -B build \
            -D CMAKE_C_COMPILER=clang \
            -D CMAKE_CXX_COMPILER=clang++ \
            -DLLVM_ENABLE_PROJECTS="clang;lld;clang-tools-extra;lldb" \
            -DCMAKE_INSTALL_PREFIX=llvm-${{ env.LLVM_VERSION }}-macos-arm \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_LIBCXX=ON \
            -DLLVM_ENABLE_THREADS=ON \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DLLVM_ENABLE_LIBATOMIC=OFF \
            -DBUILD_SHARED_LIBS=OFF \
            -DLLVM_BUILD_STATIC=ON \
            -DLLDB_ENABLE_PYTHON=OFF \
            -DLLDB_ENABLE_LUA=OFF \
            -DLLDB_ENABLE_LIBXML2=OFF \
            -DLLDB_ENABLE_LZMA=OFF \
            -DLLDB_ENABLE_CURSES=OFF \
            -DLLDB_ENABLE_LIBEDIT=OFF \
            -DLLVM_BUILD_EXAMPLES=OFF -DLLVM_INCLUDE_EXAMPLES=OFF \
            -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_UTILS=OFF \
            -DLLVM_BUILD_TESTS=OFF -DLLVM_INCLUDE_TESTS=OFF \
            -DLLVM_BUILD_BENCHMARKS=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF \
            -DLLVM_ENABLE_ASSERTIONS=OFF -DCLANG_INCLUDE_TESTS=OFF -DLLDB_INCLUDE_TESTS=OFF \
            -DLIBCLANG_BUILD_STATIC=ON -DLLVM_ENABLE_PIC=OFF

      - name: Build LLVM
        run: |
          cd llvm
          cmake --build build --config Release

      - name: Install LLVM
        run: |
          cd llvm
          cmake --install build

      - name: tar.gz files
        run: |
          cd llvm/llvm-${{ env.LLVM_VERSION }}-macos-arm
          tar -cvzf ../../llvm-${{ env.LLVM_VERSION }}-macos-arm.tar.gz *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: llvm-${{ env.LLVM_VERSION }}-macos-arm
          path: llvm-${{ env.LLVM_VERSION }}-macos-arm.tar.gz
