name: Build LLVM Windows (AMD64)

on:
  push:
    branches:
      - run-actions
      - windows-actions
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  LLVM_VERSION: "20.1.8"

jobs:
  build-llvm-windows-AMD64:
    runs-on: windows-2025

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: llvm/llvm-project
          ref: llvmorg-${{ env.LLVM_VERSION }}

      - name: Configure and build LLVM
        run: |
          cd llvm
          cmake -G Ninja -B build -S . \
            -DLLVM_ENABLE_PROJECTS="clang;lld;clang-tools-extra;lldb;compiler-rt" \
            -DCMAKE_INSTALL_PREFIX=llvm-${{ env.LLVM_VERSION }}-windows \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DLLVM_BUILD_STATIC=OFF \
            -DLLVM_BUILD_EXAMPLES=OFF -DLLVM_INCLUDE_EXAMPLES=OFF \
            -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_UTILS=OFF \
            -DLLVM_BUILD_TESTS=OFF -DLLVM_INCLUDE_TESTS=OFF \
            -DLLVM_BUILD_BENCHMARKS=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF \
            -DLLVM_ENABLE_ASSERTIONS=OFF -DCLANG_INCLUDE_TESTS=OFF -DLLDB_INCLUDE_TESTS=OFF
          cmake --build build --config Release
          cmake --install build
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: llvm-${{ env.LLVM_VERSION }}-windows
          path: llvm/llvm-${{ env.LLVM_VERSION }}-windows
